version: '3.7'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: WBTracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    container_name: wbtracker-db

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8000:8000"
    container_name: wbtracker-server
