"""add product table

Revision ID: 4d0aa881066b
Revises:
Create Date: 2024-02-16 02:50:33.842740

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d0aa881066b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'products',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False,
            comment='Уникальный идентификатор товара'
        ),
        sa.Column(
            'dt',
            sa.DateTime(),
            nullable=True,
            comment='Дата добавления товара'
        ),
        sa.Column(
            'nm_id',
            sa.Integer(),
            nullable=True,
            comment='Идентификатор номенклатуры товара'
        ),
        sa.Column(
            'name',
            sa.String(),
            nullable=True,
            comment='Название товара'
        ),
        sa.Column(
            'brand',
            sa.String(),
            nullable=True,
            comment='Бренд товара'
        ),
        sa.Column(
            'brand_id',
            sa.Integer(),
            nullable=True,
            comment='Идентификатор бренда'
        ),
        sa.Column(
            'site_brand_id',
            sa.Integer(),
            nullable=True,
            comment='Идентификатор бренда на сайте'
        ),
        sa.Column(
            'supplier_id',
            sa.Integer(),
            nullable=True,
            comment='Идентификатор поставщика'
        ),
        sa.Column(
            'sale',
            sa.Float(),
            nullable=True,
            comment='Товар находится на распродаже или нет'
        ),
        sa.Column(
            'price',
            sa.Float(),
            nullable=True,
            comment='Цена товара без скидки'
        ),
        sa.Column(
            'sale_price',
            sa.Float(),
            nullable=True,
            comment='Цена товара со скидкой'
        ),
        sa.Column(
            'rating',
            sa.Float(),
            nullable=True,
            comment='Рейтинг товара'
        ),
        sa.Column(
            'feedbacks',
            sa.Integer(),
            nullable=True,
            comment='Количество отзывов о товаре'
        ),
        sa.Column(
            'colors',
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
            comment='Список цветов товара'
        ),
        sa.PrimaryKeyConstraint('id'),
        comment='Таблица, содержащая информацию о товарах'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
